export const PERMISSIONS = {
  // Kegiatan
  CREATE_KEGIATAN: 'create:kegiatan',
  READ_KEGIATAN: 'read:kegiatan',
  UPDATE_KEGIATAN: 'update:kegiatan',
  DELETE_KEGIATAN: 'delete:kegiatan',

  // Proposal
  CREATE_PROPOSAL: 'create:proposal',
  READ_PROPOSAL: 'read:proposal',
  UPDATE_PROPOSAL: 'update:proposal',
  DELETE_PROPOSAL: 'delete:proposal',

  // RAB
  CREATE_RAB: 'create:rab',
  READ_RAB: 'read:rab',
  UPDATE_RAB: 'update:rab',
  DELETE_RAB: 'delete:rab',

  // Donasi
  CREATE_DONASI: 'create:donasi',
  READ_DONASI: 'read:donasi',
  UPDATE_DONASI: 'update:donasi',
  DELETE_DONASI: 'delete:donasi',
  CONFIRM_DONASI: 'confirm:donasi',

  // Pengeluaran
  CREATE_PENGELUARAN: 'create:pengeluaran',
  READ_PENGELUARAN: 'read:pengeluaran',
  UPDATE_PENGELUARAN: 'update:pengeluaran',
  DELETE_PENGELUARAN: 'delete:pengeluaran',
  APPROVE_PENGELUARAN: 'approve:pengeluaran',

  // Agenda
  CREATE_AGENDA: 'create:agenda',
  READ_AGENDA: 'read:agenda',
  UPDATE_AGENDA: 'update:agenda',
  DELETE_AGENDA: 'delete:agenda',

  // Dokumentasi
  CREATE_DOKUMENTASI: 'create:dokumentasi',
  READ_DOKUMENTASI: 'read:dokumentasi',
  UPDATE_DOKUMENTASI: 'update:dokumentasi',
  DELETE_DOKUMENTASI: 'delete:dokumentasi',

  // User
  CREATE_USER: 'create:user',
  READ_USER: 'read:user',
  UPDATE_USER: 'update:user',
  DELETE_USER: 'delete:user',

  // Laporan
  READ_LAPORAN: 'read:laporan',
  EXPORT_LAPORAN: 'export:laporan',
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

export interface RBACUser {
  id: string
  role: {
    name: string
  }
}

const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  SUPER_ADMIN: [
    PERMISSIONS.CREATE_KEGIATAN,
    PERMISSIONS.READ_KEGIATAN,
    PERMISSIONS.UPDATE_KEGIATAN,
    PERMISSIONS.DELETE_KEGIATAN,
    PERMISSIONS.CREATE_PROPOSAL,
    PERMISSIONS.READ_PROPOSAL,
    PERMISSIONS.UPDATE_PROPOSAL,
    PERMISSIONS.DELETE_PROPOSAL,
    PERMISSIONS.CREATE_RAB,
    PERMISSIONS.READ_RAB,
    PERMISSIONS.UPDATE_RAB,
    PERMISSIONS.DELETE_RAB,
    PERMISSIONS.CREATE_DONASI,
    PERMISSIONS.READ_DONASI,
    PERMISSIONS.UPDATE_DONASI,
    PERMISSIONS.DELETE_DONASI,
    PERMISSIONS.CONFIRM_DONASI,
    PERMISSIONS.CREATE_PENGELUARAN,
    PERMISSIONS.READ_PENGELUARAN,
    PERMISSIONS.UPDATE_PENGELUARAN,
    PERMISSIONS.DELETE_PENGELUARAN,
    PERMISSIONS.APPROVE_PENGELUARAN,
    PERMISSIONS.CREATE_AGENDA,
    PERMISSIONS.READ_AGENDA,
    PERMISSIONS.UPDATE_AGENDA,
    PERMISSIONS.DELETE_AGENDA,
    PERMISSIONS.CREATE_DOKUMENTASI,
    PERMISSIONS.READ_DOKUMENTASI,
    PERMISSIONS.UPDATE_DOKUMENTASI,
    PERMISSIONS.DELETE_DOKUMENTASI,
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.READ_USER,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.DELETE_USER,
    PERMISSIONS.READ_LAPORAN,
    PERMISSIONS.EXPORT_LAPORAN,
  ],
  ADMIN: [
    PERMISSIONS.CREATE_KEGIATAN,
    PERMISSIONS.READ_KEGIATAN,
    PERMISSIONS.UPDATE_KEGIATAN,
    PERMISSIONS.DELETE_KEGIATAN,
    PERMISSIONS.CREATE_PROPOSAL,
    PERMISSIONS.READ_PROPOSAL,
    PERMISSIONS.UPDATE_PROPOSAL,
    PERMISSIONS.CREATE_RAB,
    PERMISSIONS.READ_RAB,
    PERMISSIONS.UPDATE_RAB,
    PERMISSIONS.READ_DONASI,
    PERMISSIONS.UPDATE_DONASI,
    PERMISSIONS.READ_PENGELUARAN,
    PERMISSIONS.CREATE_AGENDA,
    PERMISSIONS.READ_AGENDA,
    PERMISSIONS.UPDATE_AGENDA,
    PERMISSIONS.DELETE_AGENDA,
    PERMISSIONS.CREATE_DOKUMENTASI,
    PERMISSIONS.READ_DOKUMENTASI,
    PERMISSIONS.UPDATE_DOKUMENTASI,
    PERMISSIONS.READ_LAPORAN,
    PERMISSIONS.EXPORT_LAPORAN,
  ],
  BENDAHARA: [
    PERMISSIONS.READ_KEGIATAN,
    PERMISSIONS.READ_PROPOSAL,
    PERMISSIONS.READ_RAB,
    PERMISSIONS.UPDATE_RAB,
    PERMISSIONS.READ_DONASI,
    PERMISSIONS.CONFIRM_DONASI,
    PERMISSIONS.UPDATE_DONASI,
    PERMISSIONS.READ_PENGELUARAN,
    PERMISSIONS.APPROVE_PENGELUARAN,
    PERMISSIONS.READ_LAPORAN,
    PERMISSIONS.EXPORT_LAPORAN,
  ],
  OPERATOR: [
    PERMISSIONS.READ_KEGIATAN,
    PERMISSIONS.UPDATE_KEGIATAN,
    PERMISSIONS.READ_PROPOSAL,
    PERMISSIONS.CREATE_PROPOSAL,
    PERMISSIONS.READ_RAB,
    PERMISSIONS.READ_DONASI,
    PERMISSIONS.READ_PENGELUARAN,
    PERMISSIONS.CREATE_PENGELUARAN,
    PERMISSIONS.READ_AGENDA,
    PERMISSIONS.CREATE_AGENDA,
    PERMISSIONS.UPDATE_AGENDA,
    PERMISSIONS.READ_DOKUMENTASI,
    PERMISSIONS.CREATE_DOKUMENTASI,
    PERMISSIONS.UPDATE_DOKUMENTASI,
  ],
  DONATUR: [
    PERMISSIONS.READ_KEGIATAN,
    PERMISSIONS.READ_PROPOSAL,
    PERMISSIONS.READ_RAB,
    PERMISSIONS.CREATE_DONASI,
    PERMISSIONS.READ_DONASI,
    PERMISSIONS.READ_AGENDA,
    PERMISSIONS.READ_DOKUMENTASI,
  ],
}

export function hasPermission(user: RBACUser, permission: Permission): boolean {
  const rolePermissions = ROLE_PERMISSIONS[user.role.name]
  if (!rolePermissions) return false
  return rolePermissions.includes(permission)
}

export function hasRole(user: RBACUser, roleName: string): boolean {
  return user.role.name === roleName
}

export function getPermissionsForRole(roleName: string): Permission[] {
  return ROLE_PERMISSIONS[roleName] || []
}
